// AUTO-GENERATED: This file is generated by the `generator` package

import 'endpoint.dart';

final rules = <String, RegionConfig>{
  '*/*': RegionConfig(
    endpoint: '{service}.{region}.amazonaws.com',
  ),
  'cn-*/*': RegionConfig(
    endpoint: '{service}.{region}.amazonaws.com.cn',
  ),
  'us-iso-*/*': _usIso,
  'us-isob-*/*': _usIsob,
  '*/budgets': _globalSSL,
  '*/cloudfront': _globalSSL,
  '*/sts': _globalSSL,
  '*/importexport': RegionConfig(
    endpoint: '{service}.amazonaws.com',
    globalEndpoint: true,
    signatureVersion: 'v2',
  ),
  '*/route53': _globalSSL,
  'cn-*/route53': RegionConfig(
    endpoint: '{service}.amazonaws.com.cn',
    globalEndpoint: true,
    signingRegion: 'cn-northwest-1',
  ),
  'us-gov-*/route53': _globalGovCloud,
  'us-iso-*/route53': RegionConfig(
    endpoint: '{service}.c2s.ic.gov',
    globalEndpoint: true,
    signingRegion: 'us-iso-east-1',
  ),
  'us-isob-*/route53': RegionConfig(
    endpoint: '{service}.sc2s.sgov.gov',
    globalEndpoint: true,
    signingRegion: 'us-isob-east-1',
  ),
  '*/waf': _globalSSL,
  '*/iam': _globalSSL,
  'cn-*/iam': RegionConfig(
    endpoint: '{service}.cn-north-1.amazonaws.com.cn',
    globalEndpoint: true,
    signingRegion: 'cn-north-1',
  ),
  'us-gov-*/iam': _globalGovCloud,
  'us-gov-*/sts': RegionConfig(
    endpoint: '{service}.{region}.amazonaws.com',
  ),
  'us-gov-west-1/s3': _s3signature,
  'us-west-1/s3': _s3signature,
  'us-west-2/s3': _s3signature,
  'eu-west-1/s3': _s3signature,
  'ap-southeast-1/s3': _s3signature,
  'ap-southeast-2/s3': _s3signature,
  'ap-northeast-1/s3': _s3signature,
  'sa-east-1/s3': _s3signature,
  'us-east-1/s3': RegionConfig(
    endpoint: '{service}.amazonaws.com',
    signatureVersion: 's3',
  ),
  'us-east-1/sdb': RegionConfig(
    endpoint: '{service}.amazonaws.com',
    signatureVersion: 'v2',
  ),
  '*/sdb': RegionConfig(
    endpoint: '{service}.{region}.amazonaws.com',
    signatureVersion: 'v2',
  ),
};
final fipsRules = <String, RegionConfig>{
  '*/*': _fipsStandard,
  'us-gov-*/*': _fipsStandard,
  'us-iso-*/*': RegionConfig(
    endpoint: '{service}-fips.{region}.c2s.ic.gov',
  ),
  'us-iso-*/dms': _usIso,
  'us-isob-*/*': RegionConfig(
    endpoint: '{service}-fips.{region}.sc2s.sgov.gov',
  ),
  'us-isob-*/dms': _usIsob,
  'cn-*/*': RegionConfig(
    endpoint: '{service}-fips.{region}.amazonaws.com.cn',
  ),
  '*/api.ecr': _fipsApiEcr,
  '*/api.sagemaker': _fipsApiSagemaker,
  '*/batch': _fipsDotPrefix,
  '*/eks': _fipsDotPrefix,
  '*/models.lex': _fipsModelsLex,
  '*/runtime.lex': _fipsRuntimeLex,
  '*/runtime.sagemaker': RegionConfig(
    endpoint: 'runtime-fips.sagemaker.{region}.amazonaws.com',
  ),
  '*/iam': _fipsWithoutRegion,
  '*/route53': _fipsWithoutRegion,
  '*/transcribe': _fipsDotPrefix,
  '*/waf': _fipsWithoutRegion,
  'us-gov-*/transcribe': _fipsDotPrefix,
  'us-gov-*/api.ecr': _fipsApiEcr,
  'us-gov-*/api.sagemaker': _fipsApiSagemaker,
  'us-gov-*/models.lex': _fipsModelsLex,
  'us-gov-*/runtime.lex': _fipsRuntimeLex,
  'us-gov-*/acm-pca': _fipsWithServiceOnly,
  'us-gov-*/batch': _fipsWithServiceOnly,
  'us-gov-*/config': _fipsWithServiceOnly,
  'us-gov-*/eks': _fipsWithServiceOnly,
  'us-gov-*/elasticmapreduce': _fipsWithServiceOnly,
  'us-gov-*/identitystore': _fipsWithServiceOnly,
  'us-gov-*/dynamodb': _fipsWithServiceOnly,
  'us-gov-*/elasticloadbalancing': _fipsWithServiceOnly,
  'us-gov-*/guardduty': _fipsWithServiceOnly,
  'us-gov-*/monitoring': _fipsWithServiceOnly,
  'us-gov-*/resource-groups': _fipsWithServiceOnly,
  'us-gov-*/runtime.sagemaker': _fipsWithServiceOnly,
  'us-gov-*/servicecatalog-appregistry': _fipsWithServiceOnly,
  'us-gov-*/servicequotas': _fipsWithServiceOnly,
  'us-gov-*/ssm': _fipsWithServiceOnly,
  'us-gov-*/sts': _fipsWithServiceOnly,
  'us-gov-*/support': _fipsWithServiceOnly,
  'us-gov-west-1/states': _fipsWithServiceOnly,
  'us-iso-east-1/elasticfilesystem': RegionConfig(
    endpoint: 'elasticfilesystem-fips.{region}.c2s.ic.gov',
  ),
  'us-gov-west-1/organizations': _fipsWithServiceOnly,
  'us-gov-west-1/route53': RegionConfig(
    endpoint: 'route53.us-gov.amazonaws.com',
  ),
};
final dualstackRules = <String, RegionConfig>{
  '*/*': RegionConfig(
    endpoint: '{service}.{region}.api.aws',
  ),
  'cn-*/*': RegionConfig(
    endpoint: '{service}.{region}.api.amazonwebservices.com.cn',
  ),
  '*/s3': _dualstackLegacy,
  'cn-*/s3': _dualstackLegacyCn,
  '*/s3-control': _dualstackLegacy,
  'cn-*/s3-control': _dualstackLegacyCn,
  'ap-south-1/ec2': _dualstackLegacyEc2,
  'eu-west-1/ec2': _dualstackLegacyEc2,
  'sa-east-1/ec2': _dualstackLegacyEc2,
  'us-east-1/ec2': _dualstackLegacyEc2,
  'us-east-2/ec2': _dualstackLegacyEc2,
  'us-west-2/ec2': _dualstackLegacyEc2,
};
final dualstackFipsRules = <String, RegionConfig>{
  '*/*': RegionConfig(
    endpoint: '{service}-fips.{region}.api.aws',
  ),
  'cn-*/*': RegionConfig(
    endpoint: '{service}-fips.{region}.api.amazonwebservices.com.cn',
  ),
  '*/s3': _dualstackFipsLegacy,
  'cn-*/s3': _dualstackFipsLegacyCn,
  '*/s3-control': _dualstackFipsLegacy,
  'cn-*/s3-control': _dualstackFipsLegacyCn,
};

final _globalSSL = RegionConfig(
  endpoint: 'https://{service}.amazonaws.com',
  globalEndpoint: true,
  signingRegion: 'us-east-1',
);

final _globalGovCloud = RegionConfig(
  endpoint: '{service}.us-gov.amazonaws.com',
  globalEndpoint: true,
  signingRegion: 'us-gov-west-1',
);

final _s3signature = RegionConfig(
  endpoint: '{service}.{region}.amazonaws.com',
  signatureVersion: 's3',
);

final _usIso = RegionConfig(
  endpoint: '{service}.{region}.c2s.ic.gov',
);

final _usIsob = RegionConfig(
  endpoint: '{service}.{region}.sc2s.sgov.gov',
);

final _fipsStandard = RegionConfig(
  endpoint: '{service}-fips.{region}.amazonaws.com',
);

final _fipsDotPrefix = RegionConfig(
  endpoint: 'fips.{service}.{region}.amazonaws.com',
);

final _fipsWithoutRegion = RegionConfig(
  endpoint: '{service}-fips.amazonaws.com',
);

final _fipsApiEcr = RegionConfig(
  endpoint: 'ecr-fips.{region}.amazonaws.com',
);

final _fipsApiSagemaker = RegionConfig(
  endpoint: 'api-fips.sagemaker.{region}.amazonaws.com',
);

final _fipsModelsLex = RegionConfig(
  endpoint: 'models-fips.lex.{region}.amazonaws.com',
);

final _fipsRuntimeLex = RegionConfig(
  endpoint: 'runtime-fips.lex.{region}.amazonaws.com',
);

final _fipsWithServiceOnly = RegionConfig(
  endpoint: '{service}.{region}.amazonaws.com',
);

final _dualstackLegacy = RegionConfig(
  endpoint: '{service}.dualstack.{region}.amazonaws.com',
);

final _dualstackLegacyCn = RegionConfig(
  endpoint: '{service}.dualstack.{region}.amazonaws.com.cn',
);

final _dualstackFipsLegacy = RegionConfig(
  endpoint: '{service}-fips.dualstack.{region}.amazonaws.com',
);

final _dualstackFipsLegacyCn = RegionConfig(
  endpoint: '{service}-fips.dualstack.{region}.amazonaws.com.cn',
);

final _dualstackLegacyEc2 = RegionConfig(
  endpoint: 'api.ec2.{region}.aws',
);
